DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS stock;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT UNIQUE NOT NULL
);

CREATE TABLE stock (
    Date TEXT,
    Symbol TEXT NOT NULL,
    Open REAL NOT NULL,
    High REAL NOT NULL,
    Low REAL NOT NULL,
    PRIMARY KEY(Date, Symbol)
);